endpoints.prometheus.enabled: true

logging:
  pattern.level: "correlation-id=%X{x-correlation-id}"
  level:
    com.nathanrahm: info

service:
  fridgeItemMaximums:
    soda: 12

server:
  port: 8080
  ssl:
    enabled: false

spring:
  datasource:
    password: password
    url: "jdbc:postgresql://postgres:5432/fridge_manager"
    username: fridge_manager
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: false

keycloak:
  auth-server-url: https://login.nathanrahm.com/auth
  public-client: true
  realm: FridgeManager
  resource: fridge-manager
  security-constraints:
    - authRoles:
        - fridgemanager
      security-collections:
        - name: "secure stuff"
          patterns:
            - "/*"
  ssl-required: external
  enabled: false

springdoc:
  swagger-ui:
    path: /

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true