apiVersion: v1
kind: ConfigMap
metadata:
 name: fridge-manager
data:
 bootstrap.properties: |
  vault.pki.enabled: false
  spring.application.name: fridge-manager
  spring.cloud.vault.enabled: true
  spring.cloud.vault.host: vault.vault.svc.cluster.local
  spring.cloud.vault.port: 8200
  spring.cloud.vault.scheme: http
  spring.cloud.vault.authentication: TOKEN
  spring.cloud.vault.generic.enabled: false
  spring.cloud.vault.kv.enabled: true
  spring.cloud.vault.kv.backend: projects
  spring.cloud.vault.token: {{ .Values.fridge.vaultToken }}