apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: fridge-manager
  name: fridge-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fridge-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fridge-manager
    spec:
      containers:
        - image: {{.Values.fridge.imageRepository}}/fridge-manager:@project.version@
          imagePullPolicy: IfNotPresent
          name: fridge-manager
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: application-config
              mountPath: /opt/localmovie/config
              readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: fridge-manager
            items:
              - key: bootstrap.properties
                path: bootstrap.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30